import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import StyledComponentsRegistry from 'lib/registry'
import { Wrapper } from './(acesso)/styles'
import { UserProvider } from '@/contexts/user-context'


const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <UserProvider>
          <StyledComponentsRegistry>
            <Wrapper>
              {children}
            </Wrapper>
          </StyledComponentsRegistry>
        </UserProvider>
      </body>
    </html>
  )
}
